### ISSUE TITLE
Request to use/adapt this for a project of mine

### ISSUE THREAD

**Issue by ceryliae** [copperdogma/dnd-phb-5e-index#11]
Hi,

I run a project which makes files for use with an iOS app for D&D5e.

One of the files is an HTML DM reference tool.

I would like to incorporate this into our DM screen, and I'd like permission to do so.

If you'd like to see our project, you can see it over at https://github.com/ceryliae/DnDAppFiles

Thanks for your time

**Comment by copperdogma** [comment]
I've heard of your project! Nice work.

Of course you can use it. It's open sourced here on github as you know.
Anyone can do whatever they like!

But I appreciate you asking.

You may want to hold off for a little bit, depending on what format you
want the info. A couple of other guys have volunteered to make a mobile
website version of the index and one of them already made a first pass at
parsing the plain text into json, which may be way more useful for your
app. We're still discussing the final format and how to convert and what to
use as the master file from here on out (.txt or json). I just don't want
you putting a ton of effort into converting it into json or something when
we're already on it.

Cheers!

-=Cam

**Comment by copperdogma** [comment]
I've heard of your project! Nice work.

Of course you can use it. It's open sourced here on github as you know. Anyone can do whatever they like!

But I appreciate you asking.

You may want to hold off for a little bit, depending on what format you want the info. A couple of other guys have volunteered to make a mobile website version of the index and one of them already made a first pass at parsing the plain text into json, which may be way more useful for your app. We're still discussing the final format and how to convert and what to use as the master file from here on out (.txt or json). I just don't want you putting a ton of effort into converting it into json or something when we're already on it.

Cheers!

**Comment by ceryliae** [comment]
Will the actual content of the index be changed? We're going to have to do some big changes anyway, because we're going to be making it into a table. 

So unless more entries are going to be added, there are page number changes, etc. then we'll just use this version.

**Comment by copperdogma** [comment]
Sounds good! Use it all you like.

I WILL be updating it (all files -- currently "PHB Index Improved.txt" is the master, but even if we end up using the json for the master I'll always keep that one up to date).

In fact, I just added a couple dozen new entries one minute ago.

**Comment by ceryliae** [comment]
How would you like to be attributed for the index for my project? "Github user copperdogma"?

**Comment by copperdogma** [comment]
Sure! Thanks!
