### ISSUE TITLE
DMG index?

### ISSUE THREAD

**Issue by GAZ082** [copperdogma/dnd-phb-5e-index#13]
Hi there. Planning to make one? LOVE this, specially the html-js version. <3 <3 <3

**Comment by copperdogma** [comment]
Actually I just started it! Stay tuned!

**Comment by GAZ082** [comment]
Yay! When will you jsonify the improved DMD index? :lollipop:

**Comment by copperdogma** [comment]
One of the other guys contributing actually made the original json version. We're working on a final json format. As soon as we have that squared away we'll create the DMG version. I'll leave this issue open until that happens.

**Comment by ceryliae** [comment]
Any idea how long this will take? I had a lot of positive feedback from my users about the PHB index we adapted for our project, and I would love to include the DMG as well.

**Comment by copperdogma** [comment]
Ah, I didn't realize there was so much interest! I'm working on a different side project right now, but I'll bump this to the top of my list once I'm done. Let's say two weeks until convering the DMG to json is complete?

Out of curiosity, what are you using them for?

**Comment by ceryliae** [comment]
https://github.com/ceryliae/DnDAppFiles and
http://ceryliae.github.io/5edmscreen/

**Comment by copperdogma** [comment]
Oh that thing! I use the iOS app every week! Love it! Nice work.

I'll let you know when the new one's up.

**Comment by ceryliae** [comment]
Great! Let me know whenever you finish it.

**Comment by copperdogma** [comment]
All done (finally): https://github.com/copperdogma/dnd-phb-5e-index/blob/master/DMG%20Index%20Improved.json

Enjoy!

**Comment by copperdogma** [comment]
All done:
https://github.com/copperdogma/dnd-phb-5e-index/blob/master/DMG%20Index%20Improved.json

Enjoy!

**Comment by ceryliae** [comment]
Great. Will implement it soon. 

This is the latest project I'm using it in:

www.5edmscreen.com

**Comment by copperdogma** [comment]
Very cool!
